SELECT P.PRODUCT_CODE AS PRODUCT_CODE, SUM(OFF.SALES_AMOUNT)*P.PRICE AS SALES
FROM PRODUCT P
JOIN OFFLINE_SALE OFF ON P.PRODUCT_ID = OFF.PRODUCT_ID 
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE
