/* 
조건1. 자동차 종류 : 세단 or SUV
조건2. 대여 가능 기간 : 2022년 11월 1일 ~ 11월 30일 (대여기록 테이블에 겹치면 안됨)
조건3. 30일 간 대여 금액 : 50만원 이상 200만원 미만
조회 : 자동차 ID, 자동차 종류, 대여 금액(컬럼명 FEE)
정렬 기준 : 대여 금액 내림차순, 자동차 종류 오름차순, 자동차 ID 내림차순
*/ 
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > "2022-11-01" AND START_DATE < "2022-12-01"
) AND P.DURATION_TYPE = "30일 이상"
GROUP BY C.CAR_ID
HAVING C.CAR_TYPE IN ("SUV", "세단") AND (FEE >=500000 AND FEE<2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC