-- 각 분기별 분화된 대장균 개체의 총 수 출력
SELECT 
    CASE 
        WHEN MONTH(DIFFERENTIATION_DATE) < 4 THEN CONCAT(1, 'Q')
        WHEN MONTH(DIFFERENTIATION_DATE) < 7 THEN CONCAT(2, 'Q')
        WHEN MONTH(DIFFERENTIATION_DATE) < 10 THEN CONCAT(3, 'Q')
        ELSE CONCAT(4, 'Q') END AS 'QUARTER', 
    COUNT(*) AS 'ECOLI_COUNT'
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER