SELECT I.ID, NI.FISH_NAME, I.LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO NI
ON I.FISH_TYPE = NI.FISH_TYPE
WHERE I.LENGTH IN (
    SELECT MAX(LENGTH)
    FROM FISH_INFO 
    WHERE FISH_TYPE = I.FISH_TYPE
    GROUP BY FISH_TYPE 
) 
ORDER BY I.ID;