-- 코드를 입력하세요
SELECT BOARD.TITLE AS TITLE, BOARD.BOARD_ID AS BOARD_ID, 
    REPLY.REPLY_ID AS REPLY_ID, REPLY.WRITER_ID AS WRITER_ID, 
    REPLY.CONTENTS AS CONTENTS, DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD BOARD
JOIN USED_GOODS_REPLY REPLY ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE YEAR(BOARD.CREATED_DATE) = 2022 AND MONTH(BOARD.CREATED_DATE) = 10
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE;
